query getOrderDetails($merchantUid: ID!, $orderCode: String!, $skipCustomerPhone: Boolean = false) {
  merchant(id: $merchantUid) {
    orderDetail(code: $orderCode) {
      code
      creationTime
      status
      state
      commentText
      totalPrice
      customer {
        firstName
        lastName
        phoneNumber @skip(if: $skipCustomerPhone)
      }
      delivery {
        mode
      }
      destination {
        __typename
      }
      warehouse {
        __typename
      }
      entries {
        quantity
        totalPrice
        product {
          name
        }
        merchantProduct {
          code
        }
      }
    }
  }
}
